name = "nng"
uuid = "61bf33c7-a621-40b0-bec2-8ae62975cf65"
authors = ["Guillem <guillemborrell@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
